local ew_util = require '__eternal-winter__.prototypes.ew-util'
local hit_effects = require '__base__.prototypes.entity.hit-effects'
local sounds = require '__base__.prototypes.entity.sounds'
local se_path = '__space-exploration-graphics__/graphics/icons/'
local item_order = 'r[radioactivity]-'
local recipe_order = 'n[radioactivity]-'
local rc_animation_speed = 1 / 5
local alien_artifact = 'cb_alien_cold_artifact'

data:extend({
  -- Recipe cat.
  {
    name = 'll-radioactivity',
    type = 'recipe-category'
  },
  -- Module cat.
  {
    name = 'll-radioactivity',
    type = 'module-category'
  },
  -- [[ Items ]]
  -- Alien
  {
    name = 'll-alien',
    type = 'module',
    icon = '__base__/graphics/icons/big-biter.png',
    icon_mipmaps = 4,
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'b',
    stack_size = 50,
    category = 'll-radioactivity',
    tier = 1,
    effect = { speed = { bonus = 1 }, pollution = { bonus = 1 } },
    limitation = {},
    limitation_message_key = 'll-radioactivity',
    beacon_tint = { primary = { r = 1, g = 0.5, b = 0, a = 1 }, secondary = { r = 1, g = 0.5, b = 0, a = 1 } },
    art_style = 'vanilla',
    requires_beacon_alt_mode = false,
  },
  -- Alien sample
  {
    name = 'll-alien-sample',
    type = 'item',
    icon = se_path .. 'vitamelange-bloom.png',
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'd',
    stack_size = 50,
  },
  -- Alien seed
  {
    name = 'll-alien-seed',
    type = 'item',
    icon = se_path .. 'vatling.png',
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'c',
    stack_size = 50,
  },
  -- Capsule
  {
    name = 'll-capsule',
    type = 'item',
    icon = se_path .. 'catalogue/deep-1.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'intermediate-product',
    order = item_order .. 'j',
    stack_size = 50,
  },
  -- Contaminated shell
  {
    name = 'll-contaminated-shell',
    type = 'item',
    icon = se_path .. 'catalogue/material-1.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'intermediate-product',
    order = item_order .. 'l',
    stack_size = 50,
  },
  -- Contaminated waste
  {
    name = 'll-contaminated-waste',
    type = 'fluid',
    icon = se_path .. 'fluid/chemical-gel.png',
    icon_size = 64,
    icon_mipmaps = 4,
    base_color = { r = 160, g = 82, b = 45 },
    flow_color = { r = 160, g = 82, b = 45 },
    default_temperature = 315,
  },
  -- Empty frame
  {
    name = 'll-empty-frame',
    type = 'item',
    icon = se_path .. 'scaffold.png',
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'f',
    stack_size = 50,
  },
  -- Empty shell
  {
    name = 'll-empty-shell',
    type = 'item',
    icon = se_path .. 'catalogue/deep-insight.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'intermediate-product',
    order = item_order .. 'g',
    stack_size = 50,
  },
  -- Encapsulated explosive rocket
  {
    name = 'll-encapsulated-explosive-rocket',
    type = 'item',
    icon = se_path .. 'meteor-defence-ammo.png',
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'k',
    stack_size = 50,
  },
  -- Enriched radioactive waste
  {
    name = 'll-enriched-radioactive-waste',
    type = 'fluid',
    icon = se_path .. 'fluid/proton-stream.png',
    icon_size = 64,
    icon_mipmaps = 4,
    base_color = { r = 0, g = 255, b = 127 },
    flow_color = { r = 0, g = 255, b = 127 },
    default_temperature = 400,
  },
  -- Luna sample
  {
    name = 'll-luna-sample',
    type = 'item',
    icon = se_path .. '/astronomic/asteroid-belt.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'll-raw-material-moon',
    order = item_order .. 'e',
    stack_size = 50,
  },
  -- Matter artillery shell
  {
    name = 'll-matter-artillery-shell',
    type = 'item',
    icon = se_path .. 'plague-bomb.png',
    icon_size = 64,
    subgroup = 'intermediate-product',
    order = item_order .. 'm',
    stack_size = 50,
  },
  -- Radioactive alien nest
  {
    name = 'll-radioactive-alien-nest',
    type = 'item',
    icon = se_path .. 'catalogue/biological-2.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'intermediate-product',
    order = item_order .. 'i',
    stack_size = 50,
  },
  -- Radioactive shell
  {
    name = 'll-radioactive-shell',
    type = 'item',
    icon = se_path .. 'catalogue/biological-insight.png',
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = 'intermediate-product',
    order = item_order .. '',
    stack_size = 50,
  },
  -- [[ Recipes ]]
  -- Alien
  {
    name = 'll-alien',
    type = 'recipe',
    category = 'll-radioactivity',
    energy_required = 300,
    ingredients = {
      { type = 'item', name = 'll-silicon', amount = 5 },
      { type = 'item', name = 'sulfur', amount = 3 },
      { type = 'item', name = 'll-luna-sample', amount = 1 },
      { type = 'item', name = alien_artifact, amount = 1 },
      { type = 'fluid', name = 'll-oxygen', amount = 1000 },
    },
    results = { { type = 'item', name = 'll-alien-seed', amount = 10 },
                { type = 'item', name = 'll-alien', amount = 1 } },
    main_product = 'll-alien',
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Alien artifact
  {
    name = 'll-alien-artifact',
    type = 'recipe',
    category = 'crafting',
    energy_required = 150,
    ingredients = {
      { type = 'item', name = alien_artifact, amount = 5, catalyst_amount = 5 },
      { type = 'item', name = 'll-luna-sample', amount = 10 },
      { type = 'item', name = 'll-ice', amount = 200 },
    },
    results = {
      { type = 'item', name = alien_artifact, amount_min = 1, amount_max = 80, probability = 0.2 },
      { type = 'item', name = 'll-rich-moon-rock', amount_min = 5, amount_max = 20, probability = 0.8 },
    },
    main_product = alien_artifact,
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Alien sample
  {
    name = 'll-alien-sample',
    type = 'recipe',
    category = 'centrifuging',
    energy_required = 70,
    ingredients = {
      { type = 'item', name = 'll-radioactive-shell', amount = 5 },
      { type = 'item', name = 'll-encapsulated-explosive-rocket', amount = 10 },
      { type = 'item', name = 'll-alien-seed', amount = 30 },
    },
    results = {
      { type = 'item', name = 'll-contaminated-shell', amount = 5 },
      { type = 'item', name = 'll-capsule', amount = 10 },
      { type = 'item', name = 'll-alien-sample', amount = 30 },
    },
    main_product = 'll-alien-sample',
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Alien seed
  {
    name = 'll-alien-seed',
    type = 'recipe',
    category = 'centrifuging',
    energy_required = 20,
    ingredients = {
      { type = 'item', name = 'll-enriched-radioactive-waste-barrel', amount = 3 },
      { type = 'item', name = 'water-barrel', amount = 10 },
      { type = 'item', name = 'll-matter-artillery-shell', amount = 1 },
      { type = 'item', name = 'll-alien', amount = 5 },
      { type = 'item', name = 'explosives', amount = 2 },
    },
    results = {
      { type = 'item', name = 'empty-barrel', amount = 13 },
      { type = 'item', name = 'll-alien-seed', amount = 10 },
      { type = 'item', name = 'll-matter-artillery-shell', amount = 1, probability = 0.999 },
    },
    main_product = 'll-alien-seed',
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Capsule
  {
    name = 'll-capsule',
    type = 'recipe',
    category = 'crafting',
    energy_required = 5,
    ingredients = {
      { type = 'item', name = 'iron-stick', amount = 15 },
      { type = 'item', name = 'll-aluminium-plate', amount = 5 },
      { type = 'item', name = 'iron-plate', amount = 2 },
    },
    results = { { type = 'item', name = 'll-capsule', amount = 1 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Contaminated waste
  {
    name = 'll-contaminated-waste',
    type = 'recipe',
    category = 'chemistry',
    energy_required = 4,
    ingredients = {
      { type = 'item', name = 'll-contaminated-shell', amount = 5 },
      { type = 'fluid', name = 'steam', amount = 25, minimum_temperature = 315 },
    },
    results = { { type = 'fluid', name = 'll-contaminated-waste', amount = 50 } },
    crafting_machine_tint = {
      primary    = { r = 255, g = 215, b = 0 },
      secondary  = { r = 255, g = 215, b = 0 },
      tertiary   = { r = 255, g = 215, b = 0 },
      quaternary = { r = 255, g = 215, b = 0 },
    },
    subgroup = 'fluid-recipes',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  {
    name = 'll-empty-shell-recycling',
    type = 'recipe',
    category = 'chemistry',
    icons = {
      { icon = se_path .. 'catalogue/deep-insight.png', icon_size = 64, icon_mipmaps = 4 },
      { icon = se_path .. 'fluid/chemical-gel.png', icon_size = 64, icon_mipmaps = 4, scale = 0.33, shift = { -8, 8 } },
      { icon = se_path .. 'transition-arrow.png', icon_size = 64, icon_mipmaps = 1, scale = 0.5 },
    },
    energy_required = 4,
    ingredients = {
      { type = 'item', name = 'll-empty-shell', amount = 5 },
      { type = 'fluid', name = 'steam', amount = 25, minimum_temperature = 315 },
    },
    results = { { type = 'fluid', name = 'll-contaminated-waste', amount = 50 } },
    crafting_machine_tint = {
      primary    = { r = 255, g = 215, b = 0 },
      secondary  = { r = 255, g = 215, b = 0 },
      tertiary   = { r = 255, g = 215, b = 0 },
      quaternary = { r = 255, g = 215, b = 0 },
    },
    subgroup = 'fluid-recipes',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Contaminated waste barrel
  {
    name = 'll-enriched-contaminated',
    type = 'recipe',
    category = 'crafting-with-fluid',
    energy_required = 50,
    ingredients = { { type = 'item', name = 'll-enriched-radioactive-waste-barrel', amount = 1 } },
    results = { { type = 'item', name = 'll-contaminated-waste-barrel', amount = 1 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  {
    name = 'll-uranium-contaminated',
    type = 'recipe',
    category = 'll-radioactivity',
    energy_required = 50,
    ingredients = {
      { type = 'item', name = 'empty-barrel', amount = 1 },
      { type = 'item', name = 'uranium-235', amount = 1 },
    },
    results = { { type = 'item', name = 'll-contaminated-waste-barrel', amount = 1 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Empty frame
  {
    name = 'll-empty-frame',
    type = 'recipe',
    category = 'chemistry',
    energy_required = 7,
    ingredients = {
      { type = 'item', name = 'coal', amount = 9 },
      { type = 'item', name = 'stone', amount = 5 },
      { type = 'fluid', name = 'll-red-mud', amount = 15 },
      { type = 'item', name = 'll-silica', amount = 30 },
    },
    results = { { type = 'item', name = 'll-empty-frame', amount = 7 } },
    crafting_machine_tint = {
      primary    = { r = 139, g = 5, b = 5 },
      secondary  = { r = 139, g = 5, b = 5 },
      tertiary   = { r = 139, g = 5, b = 5 },
      quaternary = { r = 139, g = 5, b = 5 },
    },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  {
    name = 'll-empty-frame-casting',
    type = 'recipe',
    category = 'chemistry',
    icons = {
      { icon = se_path .. 'scaffold.png', icon_size = 64, icon_mipmaps = 1 },
      { icon = se_path .. 'fluid/chemical-gel.png', icon_size = 64, icon_mipmaps = 4, scale = 0.4, shift = { 8, -8 } },
    },
    energy_required = 7,
    ingredients = { { type = 'fluid', name = 'll-contaminated-waste', amount = 100 } },
    results = { { type = 'item', name = 'll-empty-frame', amount = 1 } },
    crafting_machine_tint = {
      primary    = { r = 255, g = 215, b = 0 },
      secondary  = { r = 255, g = 215, b = 0 },
      tertiary   = { r = 255, g = 215, b = 0 },
      quaternary = { r = 255, g = 215, b = 0 },
    },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Empty shell
  {
    name = 'll-empty-shell',
    type = 'recipe',
    category = 'chemistry',
    energy_required = 4,
    ingredients = { { type = 'fluid', name = 'll-contaminated-waste', amount = 100 } },
    results = { { type = 'item', name = 'll-empty-shell', amount = 8 } },
    crafting_machine_tint = {
      primary    = { r = 0, g = 0, b = 0 },
      secondary  = { r = 0, g = 0, b = 0 },
      tertiary   = { r = 0, g = 0, b = 0 },
      quaternary = { r = 0, g = 0, b = 0 },
    },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  {
    name = 'll-empty-shell-2',
    type = 'recipe',
    category = 'chemistry',
    icons = {
      { icon = se_path .. 'catalogue/deep-insight.png', icon_size = 64, icon_mipmaps = 4 },
      {
        icon = '__base__/graphics/icons/fluid/steam.png',
        icon_size = 64,
        icon_mipmaps = 4,
        scale = 0.4,
        shift = { 4, -4 },
      },
    },
    energy_required = 4,
    ingredients = {
      { type = 'fluid', name = 'll-contaminated-waste', amount = 100 },
      { type = 'fluid', name = 'steam', amount = 50, minimum_temperature = 315 },
    },
    results = { { type = 'item', name = 'll-empty-shell', amount = 10 } },
    crafting_machine_tint = {
      primary    = { r = 0, g = 0, b = 0 },
      secondary  = { r = 0, g = 0, b = 0 },
      tertiary   = { r = 0, g = 0, b = 0 },
      quaternary = { r = 0, g = 0, b = 0 },
    },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Encapsulated explosive rocket
  {
    name = 'll-encapsulated-explosive-rocket',
    type = 'recipe',
    category = 'advanced-crafting',
    energy_required = 0.5,
    ingredients = {
      { type = 'item', name = 'll-capsule', amount = 1 },
      { type = 'item', name = 'explosive-rocket', amount = 1 },
    },
    results = { { type = 'item', name = 'll-encapsulated-explosive-rocket', amount = 1 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Enriched radioactive waste
  {
    name = 'll-enriched-radioactive-waste',
    type = 'recipe',
    category = 'crafting-with-fluid',
    energy_required = 5,
    ingredients = {
      { type = 'item', name = 'll-radioactive-shell', amount = 1 }
    },
    results = {
      { type = 'item', name = 'll-empty-shell', amount = 1 },
      { type = 'fluid', name = 'll-enriched-radioactive-waste', amount = 50 },
    },
    main_product = 'll-enriched-radioactive-waste',
    subgroup = 'fluid-recipes',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Luna sample
  {
    name = 'll-luna-sample',
    type = 'recipe',
    category = 'advanced-circuit-crafting',
    energy_required = 300,
    ingredients = {
      { type = 'item', name = 'll-moon-rock', amount = 100 },
      { type = 'item', name = 'll-astrocrystals', amount = 1 },
      { type = 'item', name = 'll-ice', amount = 5 },
    },
    results = { { type = 'item', name = 'll-luna-sample', amount = 1 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Matter artillery shell
  {
    name = 'll-matter-artillery-shell',
    type = 'recipe',
    category = 'll-radioactivity',
    energy_required = 140,
    ingredients = {
      { type = 'item', name = 'll-enriched-radioactive-waste-barrel', amount = 5 },
      { type = 'item', name = 'water-barrel', amount = 3 },
      { type = 'item', name = 'll-radioactive-alien-nest', amount = 1 },
      { type = 'item', name = 'artillery-shell', amount = 1 },
    },
    results = {
      { type = 'item', name = 'empty-barrel', amount = 8 },
      { type = 'item', name = 'll-contaminated-shell', amount = 1 },
      { type = 'item', name = 'll-matter-artillery-shell', amount = 1, probability = 0.01 },
    },
    main_product = 'll-matter-artillery-shell',
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Radioactive alien nest
  {
    name = 'll-radioactive-alien-nest',
    type = 'recipe',
    category = 'll-radioactivity',
    energy_required = 90,
    ingredients = {
      { type = 'item', name = 'll-enriched-radioactive-waste-barrel', amount = 1 },
      { type = 'item', name = 'uranium-238', amount = 1 },
      { type = 'item', name = 'll-alien-sample', amount = 5 },
      { type = 'item', name = 'll-empty-frame', amount = 1 },
      { type = 'item', name = 'explosive-rocket', amount = 1 },
    },
    results = {
      { type = 'item', name = 'empty-barrel', amount = 1 },
      { type = 'item', name = 'll-radioactive-alien-nest', amount = 1 },
    },
    main_product = 'll-radioactive-alien-nest',
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- Radioactive shell
  {
    name = 'll-radioactive-shell',
    type = 'recipe',
    category = 'll-radioactivity',
    energy_required = 100,
    ingredients = {
      { type = 'item', name = 'll-empty-shell', amount = 3 },
      { type = 'item', name = 'used-up-uranium-fuel-cell', amount = 1 },
    },
    results = { { type = 'item', name = 'll-radioactive-shell', amount = 3 } },
    subgroup = 'intermediate-product',
    allow_decomposition = true,
    always_show_made_in = true,
    enabled = false,
    hidden = false,
    hide_from_player_crafting = false,
  },
  -- [[ Radioactivity Center ]]
  -- Entity
  {
    type = 'assembling-machine',
    name = 'll-radioactivity-center',
    icon = '__space-exploration-graphics__/graphics/icons/plasma-generator.png',
    icon_size = 64,
    flags = { 'placeable-neutral', 'placeable-player', 'player-creation' },
    minable = { hardness = 0.2, mining_time = 0.5, result = 'll-radioactivity-center' },
    max_health = 500,
    corpse = 'big-remnants',
    dying_explosion = 'medium-explosion',
    resistances = {},
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    vehicle_impact_sound = { filename = '__base__/sound/car-metal-impact.ogg', volume = 0.65 },
    working_sound = { sound = { { filename = '__base__/sound/lab.ogg', volume = 0.8 } }, apparent_volume = 1.5 },
    collision_box = { { -3.2, -3.2 }, { 3.2, 3.2 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    drawing_box = { { -3.5, -5.5 }, { 3.5, 3.5 } },
    fluid_boxes = {
      {
        production_type = 'input',
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = -1,
        pipe_connections = { { type = 'input', position = { 0, -4 } } },
        secondary_draw_orders = { north = -1 },
      },
      {
        production_type = 'input',
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = -1,
        pipe_connections = { { type = 'input', position = { -4, 0 } } },
        secondary_draw_orders = { north = -1 },
      },
      {
        production_type = 'output',
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = 1,
        pipe_connections = { { type = 'output', position = { 0, 4 } } },
        secondary_draw_orders = { north = -1 },
      },
      {
        production_type = 'output',
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = 1,
        pipe_connections = { { type = 'output', position = { 4, 0 } } },
        secondary_draw_orders = { north = -1 },
      },
      off_when_no_fluid_recipe = true,
    },
    idle_animation = {
      layers = {
        {
          filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/base.png',
          priority = 'high',
          width = 448 / 2,
          height = 576 / 2,
          frame_count = 1,
          line_length = 1,
          repeat_count = 64,
          shift = util.by_pixel(0, -16),
          animation_speed = rc_animation_speed,
          hr_version = {
            filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/base.png',
            priority = 'high',
            width = 448,
            height = 576,
            frame_count = 1,
            line_length = 1,
            repeat_count = 64,
            shift = util.by_pixel(0, -16),
            animation_speed = rc_animation_speed,
            scale = 0.5,
          },
        },
        {
          draw_as_shadow = true,
          filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/shadow.png',
          priority = 'high',
          width = 566 / 2,
          height = 400 / 2,
          frame_count = 1,
          line_length = 1,
          repeat_count = 64,
          shift = util.by_pixel(35, 20),
          animation_speed = rc_animation_speed,
          hr_version = {
            draw_as_shadow = true,
            filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/shadow.png',
            priority = 'high',
            width = 566,
            height = 400,
            frame_count = 1,
            line_length = 1,
            repeat_count = 64,
            shift = util.by_pixel(35, 20),
            animation_speed = rc_animation_speed,
            scale = 0.5,
          },
        },
      },
    },
    animation = {
      layers = {
        {
          filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/base.png',
          priority = 'high',
          width = 448 / 2,
          height = 576 / 2,
          frame_count = 1,
          line_length = 1,
          repeat_count = 64,
          shift = util.by_pixel(0, -16),
          animation_speed = rc_animation_speed,
          hr_version = {
            filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/base.png',
            priority = 'high',
            width = 448,
            height = 576,
            frame_count = 1,
            line_length = 1,
            repeat_count = 64,
            shift = util.by_pixel(0, -16),
            animation_speed = rc_animation_speed,
            scale = 0.5,
          },
        },
        {
          priority = 'high',
          width = 1392 / 4 / 2,
          height = 1880 / 5 / 2,
          frame_count = 64,
          shift = util.by_pixel(0.5, -17),
          animation_speed = rc_animation_speed,
          stripes = {
            {
              filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/animation-1.png',
              width_in_frames = 4,
              height_in_frames = 5,
            },
            {
              filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/animation-2.png',
              width_in_frames = 4,
              height_in_frames = 5,
            },
            {
              filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/animation-3.png',
              width_in_frames = 4,
              height_in_frames = 5,
            },
            {
              filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/animation-4.png',
              width_in_frames = 4,
              height_in_frames = 1,
            },
          },
          hr_version = {
            priority = 'high',
            width = 1392 / 4,
            height = 1880 / 5,
            frame_count = 64,
            shift = util.by_pixel(0.5, -17),
            animation_speed = rc_animation_speed,
            scale = 0.5,
            stripes = {
              {
                filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/animation-1.png',
                width_in_frames = 4,
                height_in_frames = 5,
              },
              {
                filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/animation-2.png',
                width_in_frames = 4,
                height_in_frames = 5,
              },
              {
                filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/animation-3.png',
                width_in_frames = 4,
                height_in_frames = 5,
              },
              {
                filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/animation-4.png',
                width_in_frames = 4,
                height_in_frames = 1,
              },
            },
          },
        },
        {
          draw_as_shadow = true,
          filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/sr/shadow.png',
          priority = 'high',
          width = 566 / 2,
          height = 400 / 2,
          frame_count = 1,
          line_length = 1,
          repeat_count = 64,
          shift = util.by_pixel(35, 20),
          animation_speed = rc_animation_speed,
          hr_version = {
            draw_as_shadow = true,
            filename = '__space-exploration-graphics-3__/graphics/entity/plasma-generator/hr/shadow.png',
            priority = 'high',
            width = 566,
            height = 400,
            frame_count = 1,
            line_length = 1,
            repeat_count = 64,
            shift = util.by_pixel(35, 20),
            animation_speed = rc_animation_speed,
            scale = 0.5,
          },
        },
      },
    },
    crafting_categories = { 'll-radioactivity' },
    crafting_speed = 1,
    energy_source = { type = 'electric', usage_priority = 'secondary-input', emissions_per_minute = 0 },
    energy_usage = '8MW',
    module_specification = { module_slots = 10, module_info_max_icon_rows = 2, module_info_max_icons_per_row = 5 },
    allowed_effects = { 'consumption', 'speed', 'pollution' },
    working_visualisations = {
      {
        effect = 'uranium-glow', -- changes alpha based on energy source light intensity
        light = { intensity = 0.6, size = 16, shift = { 0.0, 0.0 }, color = { r = 1, g = 0.5, b = 0 } },
      },
    },
    created_effect = {
      type = 'direct',
      action_delivery = {
        type = 'instant',
        source_effects = { { type = 'script', effect_id = 'll-radioactivity-center-created' } },
      },
    },
    surface_conditions = { nauvis = false, luna = { plain = true, lowland = false, mountain = true, foundation = true } },
  },
  -- Item
  {
    name = 'll-radioactivity-center',
    type = 'item',
    icon = '__space-exploration-graphics__/graphics/icons/plasma-generator.png',
    icon_size = 64,
    subgroup = 'production-machine',
    order = 'g[centrifuge]-2',
    place_result = 'll-radioactivity-center',
    stack_size = 10,
  },
  -- Recipe
  {
    type = 'recipe',
    name = 'll-radioactivity-center',
    enabled = false,
    energy_required = 15,
    ingredients = {
      { 'centrifuge', 2 },
      { 'll-aluminium-plate', 40 }
    },
    result = 'll-radioactivity-center',
  },
  -- Technology
  {
    name = 'll-radioactivity-center',
    type = 'technology',
    effects = {
      { type = 'unlock-recipe', recipe = 'll-radioactivity-center' },
      { type = 'unlock-recipe', recipe = 'll-alien-artifact' },
      { type = 'unlock-recipe', recipe = 'll-alien-sample' },
      { type = 'unlock-recipe', recipe = 'll-alien-seed' },
      { type = 'unlock-recipe', recipe = 'll-alien' },
      { type = 'unlock-recipe', recipe = 'll-capsule' },
      { type = 'unlock-recipe', recipe = 'll-contaminated-waste' },
      { type = 'unlock-recipe', recipe = 'll-empty-frame-casting' },
      { type = 'unlock-recipe', recipe = 'll-empty-frame' },
      { type = 'unlock-recipe', recipe = 'll-empty-shell' },
      { type = 'unlock-recipe', recipe = 'll-empty-shell-2' },
      { type = 'unlock-recipe', recipe = 'll-empty-shell-recycling' },
      { type = 'unlock-recipe', recipe = 'll-encapsulated-explosive-rocket' },
      { type = 'unlock-recipe', recipe = 'll-enriched-contaminated' },
      { type = 'unlock-recipe', recipe = 'll-enriched-radioactive-waste' },
      { type = 'unlock-recipe', recipe = 'll-luna-sample' },
      { type = 'unlock-recipe', recipe = 'll-matter-artillery-shell' },
      { type = 'unlock-recipe', recipe = 'll-radioactive-alien-nest' },
      { type = 'unlock-recipe', recipe = 'll-radioactive-shell' },
      { type = 'unlock-recipe', recipe = 'll-uranium-contaminated' },
    },
    icon = '__space-exploration-graphics__/graphics/technology/plasma-generator.png',
    icon_size = 128,
    order = 'e-g',
    prerequisites = { 'll-space-science-pack' },
    unit = {
      count = 350,
      ingredients = {
        { 'automation-science-pack', 1 },
        { 'logistic-science-pack', 1 },
        { 'chemical-science-pack', 1 },
        { 'production-science-pack', 1 },
        { 'utility-science-pack', 1 },
        { 'll-space-science-pack', 1 },
      },
      time = 60,
    },
  },
})

ew_util.allow_productivity('ll-alien-artifact')
ew_util.allow_productivity('ll-luna-sample')
ew_util.allow_productivity('ll-empty-frame')
ew_util.allow_productivity('ll-empty-frame-casting')
ew_util.allow_productivity('ll-capsule')

ew_util.whitelist_recipes('ll-alien', {
  'll-alien',
  'll-matter-artillery-shell',
  'll-radioactive-alien-nest',
  'll-radioactive-alien-nest',
  'll-radioactive-shell',
  'll-uranium-contaminated',
})
